<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-05-22T13:43:53+10:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'Australia/Melbourne',
    'api_keys' => [
        'google' => [
            'maps' => '',
        ],
    ],
];
