<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-05-22T13:48:25+10:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      api.enabled
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.5.2',
    'version_db_installed' => '20190925072210',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1590119033,
    ],
    'calendar' => [
        'topic_attribute' => 'event_categories',
    ],
    'api' => [
        'enabled' => true,
    ],
];
