<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-05-22T13:41:58+10:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'localC5',
        ],
    ],
];
